### ISSUE TITLE
MSVCR120.dll missing

### ISSUE THREAD

**Issue by vutrulavotann** [christian-korneck/firefox_add-certs#6]
I got this message when "MSVCR120.dll missing".
Could you please upload the version without depend on this dll ?

**Comment by adlerweb** [comment]
To quote the readme: "the bundled certutil.exe might require [vcredist 12.0/2013 32bit](http://www.microsoft.com/en-us/download/details.aspx?id=40784)"

**Comment by vutrulavotann** [comment]
Thank you for replying, is there anyway that I can build it to run without vcredist 12.0 ?

**Comment by adlerweb** [comment]
AFAIK the software is written in VC++, so the runtime has to be present for it to run. You might be able to bundle the runtime into the .exe or [throw the DLLs in the same directory](https://msdn.microsoft.com/en-us/library/ms235299.aspx), however this way it will get vastly bigger and you do not get automatic updates - as such possibly spreading files with known security issues. Since VCRedist is a prerequisite for a lot of other software you might just want to (silently) install it before running the binary.

**Comment by vutrulavotann** [comment]
I got it, thank you :)
